In [1]:
import pandas as pd
df_copy = pd.read_csv('data.csv')
df = df_copy.copy()

In [2]:
df

,customerkey,total,cohort_year,customer_group,m_1,m_3,m_6,m_12
0,15,2217.406439,2021,Medium Value,0,0,0,0
1,406,2193.415412,2021,Medium Value,0,0,0,0
2,545,3551.473073,2023,High Value,0,0,0,0
3,649,2313.978416,2022,Medium Value,0,0,0,0
4,688,16909.040929,2023,High Value,0,0,0,0
...,...,...,...,...,...,...,...,...
23991,2099511,7431.552000,2020,High Value,0,0,0,0
23992,2099603,4914.000000,2022,High Value,0,0,0,0
23993,2099656,10404.677800,2023,High Value,0,1,1,1
23994,2099697,38.201100,2022,Low Value,0,0,0,0
23995,2099743,1068.080000,2022,Medium Value,0,0,0,1

In [19]:
df_retantion = df[['customerkey', 'cohort_year', 'm_1', 'm_3', 'm_6', 'm_12']].copy()

In [20]:
df_retantion

       customerkey  cohort_year  m_1  m_3  m_6  m_12
0               15         2021    0    0    0     0
1              406         2021    0    0    0     0
2              545         2023    0    0    0     0
3              649         2022    0    0    0     0
4              688         2023    0    0    0     0
...            ...          ...  ...  ...  ...   ...
23991      2099511         2020    0    0    0     0
23992      2099603         2022    0    0    0     0
23993      2099656         2023    0    1    1     1
23994      2099697         2022    0    0    0     0
23995      2099743         2022    0    0    0     1

[23996 rows x 6 columns]

In [23]:
df_melted = df_retantion.melt(id_vars=['customerkey', 'cohort_year'], value_vars=df_retantion.columns[1:], value_name='retirned_customer', var_name='month')

In [25]:
df_melted['month'] = df_melted['month'].str.replace('m_', 'Month ')

In [26]:
df_melted

       customerkey  cohort_year     month  retirned_customer
0               15         2021   Month 1                  0
1              406         2021   Month 1                  0
2              545         2023   Month 1                  0
3              649         2022   Month 1                  0
4              688         2023   Month 1                  0
...            ...          ...       ...                ...
95979      2099511         2020  Month 12                  0
95980      2099603         2022  Month 12                  0
95981      2099656         2023  Month 12                  1
95982      2099697         2022  Month 12                  0
95983      2099743         2022  Month 12                  1

[95984 rows x 4 columns]

In [27]:
df_melted.to_csv('cohort_retention.csv', sep=';', index=True, encoding='utf-8-sig')